services:
  postgres:
    image: postgres:latest
    container_name: postgres_tutor
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tutor
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres -p 5432"]
      interval: 5s
      timeout: 1s
      retries: 10
