"""add field is_don in table lessons

Revision ID: 8d9005f9f3c7
Revises: aeb50daf57b6
Create Date: 2025-02-25 19:45:42.821718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9005f9f3c7'
down_revision: Union[str, None] = 'aeb50daf57b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Добавляем колонку без NOT NULL
    op.add_column('lessons', sa.Column('is_done', sa.Boolean(), nullable=True))

    # Обновляем существующие строки
    op.execute("UPDATE lessons SET is_done = FALSE")

    # Делаем колонку NOT NULL
    op.alter_column('lessons', 'is_done', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'is_done')
    # ### end Alembic commands ###
